language: node_js
node_js:
  - node
  - 8
  - 6
script:
  - npm run ci
after_success:
- if [[ "$TRAVIS_NODE_VERSION" = "6" ]]; then './node_modules/.bin/nyc report --reporter=text-lcov | ./node_modules/.bin/coveralls'; fi
